# PURL configuration for http://purl.obolibrary.org/obo/apo

idspace: APO
base_url: /obo/apo

products:
- apo.owl: https://github.com/obophenotype/ascomycete-phenotype-ontology/raw/master/apo.owl
- apo.obo: https://github.com/obophenotype/ascomycete-phenotype-ontology/raw/master/apo.obo

term_browser: ontobee
example_terms:
- APO_0000018

entries:
- prefix: /releases/
  replacement: https://github.com/obophenotype/ascomycete-phenotype-ontology/raw/v
- exact: /
  replacement: https://github.com/obophenotype/ascomycete-phenotype-ontology/
