# PURL configuration for http://purl.obolibrary.org/obo/caro

idspace: CARO
base_url: /obo/caro

products:
- caro.owl: https://raw.githubusercontent.com/obophenotype/caro/master/caro.owl
- caro.obo: https://raw.githubusercontent.com/obophenotype/caro/master/caro.obo
- caro.json: https://raw.githubusercontent.com/obophenotype/caro/master/caro.json

term_browser: ontobee
example_terms:
- CARO_0000000

entries:
- prefix: /
  replacement: https://raw.githubusercontent.com/obophenotype/caro/master/

