# PURL configuration for http://purl.obolibrary.org/obo/cmo

idspace: CMO
base_url: /obo/cmo

products:
- cmo.owl: https://download.rgd.mcw.edu/ontology/clinical_measurement/clinical_measurement.owl
- cmo.obo: https://download.rgd.mcw.edu/ontology/clinical_measurement/clinical_measurement.obo

term_browser: ontobee
example_terms:
- CMO_0000000
