# PURL configuration for http://purl.obolibrary.org/obo/ddanat

idspace: DDANAT
base_url: /obo/ddanat

products:
- ddanat.owl: https://raw.githubusercontent.com/dictyBase/migration-data/master/ontologies/dicty_anatomy.owl
- ddanat.obo: https://raw.githubusercontent.com/dictyBase/migration-data/master/ontologies/dicty_anatomy.obo

term_browser: ontobee
example_terms:
- DDANAT_0000002
