# PURL configuration for http://purl.obolibrary.org/obo/eco

idspace: ECO
base_url: /obo/eco

products:
- eco.owl: https://raw.githubusercontent.com/evidenceontology/evidenceontology/master/eco.owl
- eco.obo: https://raw.githubusercontent.com/evidenceontology/evidenceontology/master/eco.obo

term_browser: ols
example_terms:
- ECO_0000000

entries:
- exact: /lagacy
  replacement: http://obo.cvs.sourceforge.net/viewvc/obo/obo/ontology/evidence_code.obo?view=log

- exact: /legacy
  replacement: http://obo.cvs.sourceforge.net/viewvc/obo/obo/ontology/evidence_code.obo?view=log

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/evidenceontology/evidenceontology/v

- prefix: /about/
  replacement: https://www.ebi.ac.uk/ols4/ontologies/eco/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252F
  tests:
  - from: /about/ECO_0000000
    to: https://www.ebi.ac.uk/ols4/ontologies/eco/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FECO_0000000
    
- exact: /about
  replacement: https://www.ebi.ac.uk/ols4/ontologies/eco?tab=classes/

- prefix: /
  replacement: https://raw.githubusercontent.com/evidenceontology/evidenceontology/master/

