# PURL configuration for http://purl.obolibrary.org/obo/fbdv

idspace: FBdv
base_url: /obo/fbdv

base_redirect: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/wiki

products:
- fbdv.owl: https://github.com/FlyBase/drosophila-developmental-ontology/releases/latest/download/fbdv.owl
- fbdv.obo: https://github.com/FlyBase/drosophila-developmental-ontology/releases/latest/download/fbdv.obo
- fbdv.json: https://github.com/FlyBase/drosophila-developmental-ontology/releases/latest/download/fbdv.json

term_browser: ontobee
example_terms:
- FBdv_00005370

entries:
- prefix: /releases/
  replacement: https://github.com/FlyBase/drosophila-developmental-ontology/releases/download/v

- exact: /tracker
  replacement: https://github.com/FlyBase/drosophila-developmental-ontology/issues

- exact: /downloads
  replacement: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/wiki/Download-guide

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=FBdv&iri=http://purl.obolibrary.org/obo/

- prefix: /
  replacement: https://github.com/FlyBase/drosophila-developmental-ontology/releases/latest/download/

