# PURL configuration for http://purl.obolibrary.org/obo/hp

idspace: HP
base_url: /obo/hp

base_redirect: https://github.com/obophenotype/human-phenotype-ontology

products:
- hp.owl: https://github.com/obophenotype/human-phenotype-ontology/releases/latest/download/hp.owl
- hp.obo: https://github.com/obophenotype/human-phenotype-ontology/releases/latest/download/hp.obo
- hp.json: https://github.com/obophenotype/human-phenotype-ontology/releases/latest/download/hp.json

term_browser: custom

entries:
- prefix: /releases/hpoa/
  replacement: https://github.com/obophenotype/human-phenotype-ontology/releases/download/v
  tests:
  - from: /releases/hpoa/2022-02-14/genes_to_phenotype.txt
    to: https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2022-02-14/genes_to_phenotype.txt

- prefix: /imports/
  replacement: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/src/ontology/imports/

- prefix: /components/
  replacement: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/src/ontology/components/

- prefix: /translations/
  replacement: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/src/translations/
  tests:
  - from: /translations/hp-cs.babelon.tsv
    to: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/src/translations/hp-cs.babelon.tsv

- prefix: /releases/
  replacement: https://github.com/obophenotype/human-phenotype-ontology/releases/download/v

- prefix: /tracker
  replacement: https://github.com/obophenotype/human-phenotype-ontology/issues

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=HP&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/HP_0000001
    to: http://www.ontobee.org/browser/rdf.php?o=HP&iri=http://purl.obolibrary.org/obo/HP_0000001



# HPOA files
- prefix: /hpoa/
  replacement: https://github.com/obophenotype/human-phenotype-ontology/releases/latest/download/
  tests:
  - from: /hpoa/genes_to_phenotype.txt
    to: https://github.com/obophenotype/human-phenotype-ontology/releases/latest/download/genes_to_phenotype.txt

# default
- prefix: /
  replacement: https://github.com/obophenotype/human-phenotype-ontology/releases/latest/download/
