# PURL configuration for http://purl.obolibrary.org/obo/hsapdv

idspace: HsapDv
base_url: /obo/hsapdv

products:
- hsapdv.owl: https://raw.githubusercontent.com/obophenotype/developmental-stage-ontologies/master/src/hsapdv/hsapdv.owl
- hsapdv.obo: https://raw.githubusercontent.com/obophenotype/developmental-stage-ontologies/master/src/hsapdv/hsapdv.obo

term_browser: ontobee
example_terms:
- HsapDv_0000000
