# PURL configuration for http://purl.obolibrary.org/obo/mi

idspace: MI
base_url: /obo/mi

products:
- mi.owl: https://raw.githubusercontent.com/HUPO-PSI/psi-mi-CV/master/psi-mi.owl
- mi.obo: https://raw.githubusercontent.com/HUPO-PSI/psi-mi-CV/master/psi-mi.obo

term_browser: ontobee
example_terms:
- MI_0346
