# PURL configuration for http://purl.obolibrary.org/obo/mmo

idspace: MMO
base_url: /obo/mmo

products:
- mmo.owl: https://download.rgd.mcw.edu/ontology/measurement_method/measurement_method.owl
- mmo.obo: https://download.rgd.mcw.edu/ontology/measurement_method/measurement_method.obo

term_browser: ontobee
example_terms:
- MMO_0000000
