# PURL configuration for http://purl.obolibrary.org/obo/mmusdv

idspace: MmusDv
base_url: /obo/mmusdv

products:
- mmusdv.owl: https://raw.githubusercontent.com/obophenotype/developmental-stage-ontologies/master/src/mmusdv/mmusdv.owl
- mmusdv.obo: https://raw.githubusercontent.com/obophenotype/developmental-stage-ontologies/master/src/mmusdv/mmusdv.obo

term_browser: ontobee
example_terms:
- MmusDv_0000000
