# PURL configuration for http://purl.obolibrary.org/obo/mp

idspace: MP
base_url: /obo/mp

products:
- mp.owl: http://www.informatics.jax.org/downloads/reports/mp.owl
- mp.obo: http://www.informatics.jax.org/downloads/reports/MPheno_OBO.ontology
- mp.json: http://www.informatics.jax.org/downloads/reports/mp.json

term_browser: ontobee
example_terms:
- MP_0000001

entries:
- prefix: /about/
  replacement: http://www.ebi.ac.uk/ontology-lookup/browse.do?ontName=MP&termId=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/MP_0000001
    to: http://www.ebi.ac.uk/ontology-lookup/browse.do?ontName=MP&termId=http://purl.obolibrary.org/obo/MP_0000001

- prefix: /releases/
  replacement: https://github.com/mgijax/mammalian-phenotype-ontology/releases/download/v
  tests:  
    - from: /releases/2022-04-21/mp.obo
      to: https://github.com/mgijax/mammalian-phenotype-ontology/releases/download/v2022-04-21/mp.obo

- prefix: /tracker/
  replacement: https://github.com/mgijax/mammalian-phenotype-ontology/issues

- prefix: /patterns/
  replacement: https://raw.githubusercontent.com/mgijax/mammalian-phenotype-ontology/master/src/patterns/
  
- prefix: /imports/
  replacement: https://raw.githubusercontent.com/mgijax/mammalian-phenotype-ontology/master/src/ontology/imports/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://github.com/mgijax/mammalian-phenotype-ontology/releases/latest/download/
