# PURL configuration for http://purl.obolibrary.org/obo/olatdv

idspace: OlatDv
base_url: /obo/olatdv

products:
- olatdv.owl: https://raw.githubusercontent.com/obophenotype/developmental-stage-ontologies/master/src/olatdv/olatdv.owl
- olatdv.obo: https://raw.githubusercontent.com/obophenotype/developmental-stage-ontologies/master/src/olatdv/olatdv.obo

term_browser: ontobee
example_terms:
- OlatDv_0000020
