# PURL configuration for http://purl.obolibrary.org/obo/pcl 

idspace: PCL
base_url: /obo/pcl

products:
- pcl.owl: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/master/pcl-base.owl
- pcl.obo: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/master/pcl-base.obo

term_browser: ols
example_terms:
- PCL_0011124

entries:

# purl.obolibrary.org/obo/pcl/releases/2024-01-05/pcl-base.obo
- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/v
  tests:
    - from: /releases/2024-01-05/
      to: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/v2024-01-05/

- prefix: /tracker/
  replacement: https://github.com/obophenotype/provisional_cell_ontology/issues

- prefix: /about/
  replacement: https://github.com/obophenotype/provisional_cell_ontology#readme

- exact: /bds/kg
  replacement: https://knowledge-graph-ebi.brain.allentech.org/browser/
  
- prefix: /bds/kg/
  replacement: https://knowledge-graph-ebi.brain.allentech.org/browser/

- exact: /bds/api
  replacement: https://bkp-cts-prod.aibs-bmp-prod.net/bds/

- prefix: /bds/api/
  replacement: https://bkp-cts-prod.aibs-bmp-prod.net/bds/

### generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/master/
