# PURL configuration for http://purl.obolibrary.org/obo/pdumdv

idspace: PdumDv
base_url: /obo/pdumdv

products:
- pdumdv.owl: https://raw.githubusercontent.com/obophenotype/developmental-stage-ontologies/master/src/pdumdv/pdumdv.owl
- pdumdv.obo: https://raw.githubusercontent.com/obophenotype/developmental-stage-ontologies/master/src/pdumdv/pdumdv.obo

term_browser: ontobee
example_terms:
- PdumDv_0000090
