# PURL configuration for http://purl.obolibrary.org/obo/proco

idspace: PROCO
base_url: /obo/proco

products:
- proco.owl: https://raw.githubusercontent.com/proco-ontology/proco/master/proco.owl 

term_browser: ontobee
example_terms:
- PROCO_0000001

entries:

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/proco-ontology/proco/v
  tests:
  - from: /releases/2022-04-14/proco.owl
    to: https://raw.githubusercontent.com/proco-ontology/proco/v2022-04-14/proco.owl
 
- prefix: /tracker/
  replacement: https://github.com/proco-ontology/proco/issues
  
- prefix: /about/
  replacement: http://www.ontobee.org/ontology/PROCO?iri=http://purl.obolibrary.org/obo/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/proco-ontology/proco/master/
