# PURL configuration for http://purl.obolibrary.org/obo/pw

idspace: PW
base_url: /obo/pw

products:
- pw.owl: https://download.rgd.mcw.edu/ontology/pathway/pathway.owl
- pw.obo: https://download.rgd.mcw.edu/ontology/pathway/pathway.obo

term_browser: ontobee
example_terms:
- PW_0000555
