# PURL configuration for http://purl.obolibrary.org/obo/ro

idspace: RO
base_url: /obo/ro

base_redirect: https://github.com/oborel/obo-relations

products:
- ro.owl: https://raw.githubusercontent.com/oborel/obo-relations/master/ro.owl
- ro.obo: https://raw.githubusercontent.com/oborel/obo-relations/master/ro.obo
- ro.json: https://raw.githubusercontent.com/oborel/obo-relations/master/ro.json
- ro.html: https://github.com/oborel/obo-relations

term_browser: custom
example_terms:
- RO_0001000

entries:
- exact: /docs/causal-relations
  replacement: https://github.com/oborel/obo-relations/wiki/causal-relations

- exact: /ro-idranges.owl
  replacement: https://raw.githubusercontent.com/oborel/obo-relations/master/src/ontology/ro-idranges.owl

- prefix: /releases/2015-04-12/
  replacement: https://obo-relations.googlecode.com/svn/releases/2015-04-12/

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/oborel/obo-relations/v

- prefix: /docs/
  replacement: https://oborel.github.io/obo-relations/

- prefix: /metamodel/
  replacement: https://oborel.github.io/obo-relations/metamodel/

- prefix: /about/
  replacement: https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/BFO_0000051
    to: https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http://purl.obolibrary.org/obo/BFO_0000051

- prefix: /
  replacement: https://raw.githubusercontent.com/oborel/obo-relations/master/

