# PURL configuration for http://purl.obolibrary.org/obo/rs

idspace: RS
base_url: /obo/rs

products:
- rs.owl: https://download.rgd.mcw.edu/ontology/rat_strain/rat_strain.owl
- rs.obo: https://download.rgd.mcw.edu/ontology/rat_strain/rat_strain.obo

term_browser: ontobee
example_terms:
- RS_0000457
