# PURL configuration for http://purl.obolibrary.org/obo/sbo

idspace: SBO
base_url: /obo/sbo

products:
- sbo.owl: https://raw.githubusercontent.com/EBI-BioModels/SBO/master/SBO_OWL.owl
- sbo.obo: https://raw.githubusercontent.com/EBI-BioModels/SBO/master/SBO_OBO.obo

term_browser: ontobee
example_terms:
- SBO_0000000
