# PURL configuration for http://purl.obolibrary.org/obo/spd

idspace: SPD
base_url: /obo/spd

products:
- spd.owl: https://raw.githubusercontent.com/obophenotype/spider-ontology/master/spider_comparative_biology.owl
- spd.obo: https://raw.githubusercontent.com/obophenotype/spider-ontology/master/spider_comparative_biology.obo

term_browser: ontobee
example_terms:
- SPD_0000000
