# PURL configuration for http://purl.obolibrary.org/obo/swo

idspace: SWO
base_url: /obo/swo

products:
- swo.owl: https://github.com/allysonlister/swo/raw/master/swo.owl
- swo.json: https://github.com/allysonlister/swo/raw/master/swo.json

term_browser: ols
example_terms:
- SWO_0000000

entries:
- prefix: /tracker/
  replacement: https://github.com/allysonlister/swo/issues

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://github.com/allysonlister/swo/tree/master
