# PURL configuration for http://purl.obolibrary.org/obo/vt

idspace: VT
base_url: /obo/vt

products:
- vt.owl: https://github.com/AnimalGenome/vertebrate-trait-ontology/raw/master/current_release/vt.owl
- vt.obo: https://github.com/AnimalGenome/vertebrate-trait-ontology/raw/master/current_release/vt.obo

term_browser: ontobee
example_terms:
- VT_0000001

entries:
- prefix: /avout/
  replacement: http://www.ontobee.org/browser/rdf.php?o=OBA&iri=http://purl.obolibrary.org/obo/

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=OBA&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/VT_0000001
    to: http://www.ontobee.org/browser/rdf.php?o=OBA&iri=http://purl.obolibrary.org/obo/VT_0000001

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/AnimalGenome/vertebrate-trait-ontology/master/releases/
  tests:
  - from: /releases/2024-01-17/vt.owl
    to: https://raw.githubusercontent.com/AnimalGenome/vertebrate-trait-ontology/master/releases/2024-01-17/vt.owl
