# PURL configuration for http://purl.obolibrary.org/obo/xco

idspace: XCO
base_url: /obo/xco

products:
- xco.owl: https://download.rgd.mcw.edu/ontology/experimental_condition/experimental_condition.owl
- xco.obo: https://download.rgd.mcw.edu/ontology/experimental_condition/experimental_condition.obo

term_browser: ontobee
example_terms:
- XCO_0000000
