# PURL configuration for http://purl.obolibrary.org/obo/rnao

idspace: XLMOD
base_url: /obo/xlmod

products:
- xlmod.obo: https://raw.githubusercontent.com/HUPO-PSI/xlmod-CV/main/XLMOD.obo
- xlmod.owl: https://raw.githubusercontent.com/HUPO-PSI/xlmod-CV/main/XLMOD.owl

term_browser: ontobee

entries:
- exact: /tracker
  replacement: https://github.com/HUPO-PSI/xlmod-CV/issues
